// <auto-generated />
using System;
using LearningLantern.Video.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearningLantern.Video.Migrations
{
    [DbContext(typeof(VideoContext))]
    [Migration("20220705112810_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LearningLantern.Video.Data.Models.VideoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BlobName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("LearningLantern.Video.Data.Models.VideoQuiz", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("QuizId")
                        .HasColumnType("int");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.Property<int?>("VideoModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VideoModelId");

                    b.ToTable("VideoQuiz");
                });

            modelBuilder.Entity("LearningLantern.Video.Data.Models.VideoQuiz", b =>
                {
                    b.HasOne("LearningLantern.Video.Data.Models.VideoModel", null)
                        .WithMany("QuizList")
                        .HasForeignKey("VideoModelId");
                });

            modelBuilder.Entity("LearningLantern.Video.Data.Models.VideoModel", b =>
                {
                    b.Navigation("QuizList");
                });
#pragma warning restore 612, 618
        }
    }
}
